### ISSUE TITLE
Restrict recurring event's duration

### ISSUE THREAD

**Issue by KongBorup** [KongBorup/rollespilsfabrikken-forum-calendar-frontend#23]
If a recurring event with a duration of two days is set to repeat daily, that event will show up twice on each date in the calendar. If it's set to repeat daily with a duration of a month, the events stack up continuously for each day, and a LOT of events are shown. This makes logical sense, but it unfortunately causes the calendar to crash.

A fix would be to simply not allow the users to create events whose duration is longer than the recurrence interval. An event that reccurs daily must at a maximum be a day long.

Regarding that example: should it be 24 hours at a maximum or must it not extend beyond the same day?

**Comment by albe2669** [comment]
I would say that a 24 hour limit would be ideal, as the events could then be back to back, but never overlap. Not going beyond the same day could cause issues, especially in the case of night events.
